#!/usr/bin/env bash
#Creates the file /var/run/myscript.pid containing its PID
#Displays To infinity and beyond indefinitely
#Displays I hate the kill command when receiving a SIGTERM signal
#Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT signal
#Displays Y U no love me?! when receiving a SIGINT signal

handler()
{
	signal="$1"
	if [ "$signal" = "SIGTERM" ]
	then
		echo "I hate the kill command"
		rm /var/run/myscript.pid
		exit
	elif [ "$signal" = "SIGQUIT" ]
	then
		rm /var/run/myscript.pid
		exit
	elif [ "$signal" = "SIGINT" ]
	then
		echo "Y U no love me?!"
	fi
}

echo $$ > /var/run/myscript.pid
trap "handler SIGTERM" SIGTERM
trap "handler SIGQUIT" SIGQUIT
trap "handler SIGINT" SIGINT
while true
do
	echo "To infinity and beyond"
	sleep 2
done
