#!/usr/bin/env bash
#traps the signal and prints I am invincible when receiving a SIGTERM signal

sighandler()
{
	echo "I am invincible!!!"
}

trap 'sighandler' SIGTERM

while true
do
	echo "To infinity and beyond"
	sleep 2
done
