#!/usr/bin/env bash
#prints numbers from 1 - 20 as well as if the number is unlucky
i=1
while [ $i -le 20 ]
	do
		echo $i
		case $i in
			4)
				echo "bad luck from China"
				;;
			9)
				echo "bad luck from Japan"
				;;
			17)
				echo "bad luck from Italy"
				;;
		esac
		((i++))
	done
