#!/usr/bin/env bash
#changes localhost and facebook.com in /etc/hosts

cp /etc/hosts ~/hosts.tmp
echo "127.0.0.2		localhost" > ~/hosts.tmp
echo "8.8.8.8		facebook.com" >> ~/hosts.tmp
cp -f ~/hosts.tmp /etc/hosts
